# Étape 1 : Construction de l'application
FROM node:19

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY site/LivreaPiques/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du site
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev"]