# Étape 1 : Construction de l'application
FROM node:22

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du site
COPY . .

# Exposer le port 5173 (port par défaut de Vite)
EXPOSE 5173

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host"]